/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PredictedPapersRouteImport } from './routes/predicted-papers'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IbRouteImport } from './routes/ib'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PredictedPapersIndexRouteImport } from './routes/predicted-papers/index'
import { Route as IbIndexRouteImport } from './routes/ib/index'
import { Route as BotsIndexRouteImport } from './routes/bots/index'
import { Route as IbQuestionsRouteImport } from './routes/ib/questions'
import { Route as IbNotesRouteImport } from './routes/ib/notes'
import { Route as IbFlashcardsRouteImport } from './routes/ib/flashcards'
import { Route as IbCheatsheetsRouteImport } from './routes/ib/cheatsheets'
import { Route as IbSubjectRouteImport } from './routes/ib/$subject'
import { Route as PredictedPapersSubjectSlugIndexRouteImport } from './routes/predicted-papers/$subjectSlug/index'
import { Route as IbCheatsheetsIndexRouteImport } from './routes/ib/cheatsheets/index'
import { Route as IbSubjectIndexRouteImport } from './routes/ib/$subject/index'
import { Route as PredictedPapersSubjectSlugPaperSlugRouteImport } from './routes/predicted-papers/$subjectSlug/$paperSlug'
import { Route as IbCheatsheetsIdRouteImport } from './routes/ib/cheatsheets/$id'
import { Route as IbSubjectQuestionbankRouteImport } from './routes/ib/$subject/questionbank'
import { Route as IbSubjectPredictedPapersRouteImport } from './routes/ib/$subject/predicted-papers'
import { Route as IbSubjectNotesRouteImport } from './routes/ib/$subject/notes'
import { Route as IbSubjectFlashcardsRouteImport } from './routes/ib/$subject/flashcards'
import { Route as IbSubjectCheatsheetsRouteImport } from './routes/ib/$subject/cheatsheets'
import { Route as ChatBotIdChatIdRouteImport } from './routes/chat/$botId/$chatId'
import { Route as IbSubjectTopicslugQuestionbankRouteImport } from './routes/ib/$subject/$topicslug/questionbank'
import { Route as IbSubjectTopicslugFlashcardsRouteImport } from './routes/ib/$subject/$topicslug/flashcards'
import { Route as IbSubjectNoteslugNotesRouteImport } from './routes/ib/$subject/$noteslug/notes'

const PredictedPapersRoute = PredictedPapersRouteImport.update({
  id: '/predicted-papers',
  path: '/predicted-papers',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IbRoute = IbRouteImport.update({
  id: '/ib',
  path: '/ib',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictedPapersIndexRoute = PredictedPapersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PredictedPapersRoute,
} as any)
const IbIndexRoute = IbIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IbRoute,
} as any)
const BotsIndexRoute = BotsIndexRouteImport.update({
  id: '/bots/',
  path: '/bots/',
  getParentRoute: () => rootRouteImport,
} as any)
const IbQuestionsRoute = IbQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => IbRoute,
} as any)
const IbNotesRoute = IbNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => IbRoute,
} as any)
const IbFlashcardsRoute = IbFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => IbRoute,
} as any)
const IbCheatsheetsRoute = IbCheatsheetsRouteImport.update({
  id: '/cheatsheets',
  path: '/cheatsheets',
  getParentRoute: () => IbRoute,
} as any)
const IbSubjectRoute = IbSubjectRouteImport.update({
  id: '/$subject',
  path: '/$subject',
  getParentRoute: () => IbRoute,
} as any)
const PredictedPapersSubjectSlugIndexRoute =
  PredictedPapersSubjectSlugIndexRouteImport.update({
    id: '/$subjectSlug/',
    path: '/$subjectSlug/',
    getParentRoute: () => PredictedPapersRoute,
  } as any)
const IbCheatsheetsIndexRoute = IbCheatsheetsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IbCheatsheetsRoute,
} as any)
const IbSubjectIndexRoute = IbSubjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IbSubjectRoute,
} as any)
const PredictedPapersSubjectSlugPaperSlugRoute =
  PredictedPapersSubjectSlugPaperSlugRouteImport.update({
    id: '/$subjectSlug/$paperSlug',
    path: '/$subjectSlug/$paperSlug',
    getParentRoute: () => PredictedPapersRoute,
  } as any)
const IbCheatsheetsIdRoute = IbCheatsheetsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => IbCheatsheetsRoute,
} as any)
const IbSubjectQuestionbankRoute = IbSubjectQuestionbankRouteImport.update({
  id: '/questionbank',
  path: '/questionbank',
  getParentRoute: () => IbSubjectRoute,
} as any)
const IbSubjectPredictedPapersRoute =
  IbSubjectPredictedPapersRouteImport.update({
    id: '/predicted-papers',
    path: '/predicted-papers',
    getParentRoute: () => IbSubjectRoute,
  } as any)
const IbSubjectNotesRoute = IbSubjectNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => IbSubjectRoute,
} as any)
const IbSubjectFlashcardsRoute = IbSubjectFlashcardsRouteImport.update({
  id: '/flashcards',
  path: '/flashcards',
  getParentRoute: () => IbSubjectRoute,
} as any)
const IbSubjectCheatsheetsRoute = IbSubjectCheatsheetsRouteImport.update({
  id: '/cheatsheets',
  path: '/cheatsheets',
  getParentRoute: () => IbSubjectRoute,
} as any)
const ChatBotIdChatIdRoute = ChatBotIdChatIdRouteImport.update({
  id: '/chat/$botId/$chatId',
  path: '/chat/$botId/$chatId',
  getParentRoute: () => rootRouteImport,
} as any)
const IbSubjectTopicslugQuestionbankRoute =
  IbSubjectTopicslugQuestionbankRouteImport.update({
    id: '/$topicslug/questionbank',
    path: '/$topicslug/questionbank',
    getParentRoute: () => IbSubjectRoute,
  } as any)
const IbSubjectTopicslugFlashcardsRoute =
  IbSubjectTopicslugFlashcardsRouteImport.update({
    id: '/$topicslug/flashcards',
    path: '/$topicslug/flashcards',
    getParentRoute: () => IbSubjectRoute,
  } as any)
const IbSubjectNoteslugNotesRoute = IbSubjectNoteslugNotesRouteImport.update({
  id: '/$noteslug/notes',
  path: '/$noteslug/notes',
  getParentRoute: () => IbSubjectRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ib': typeof IbRouteWithChildren
  '/login': typeof LoginRoute
  '/predicted-papers': typeof PredictedPapersRouteWithChildren
  '/ib/$subject': typeof IbSubjectRouteWithChildren
  '/ib/cheatsheets': typeof IbCheatsheetsRouteWithChildren
  '/ib/flashcards': typeof IbFlashcardsRoute
  '/ib/notes': typeof IbNotesRoute
  '/ib/questions': typeof IbQuestionsRoute
  '/bots/': typeof BotsIndexRoute
  '/ib/': typeof IbIndexRoute
  '/predicted-papers/': typeof PredictedPapersIndexRoute
  '/chat/$botId/$chatId': typeof ChatBotIdChatIdRoute
  '/ib/$subject/cheatsheets': typeof IbSubjectCheatsheetsRoute
  '/ib/$subject/flashcards': typeof IbSubjectFlashcardsRoute
  '/ib/$subject/notes': typeof IbSubjectNotesRoute
  '/ib/$subject/predicted-papers': typeof IbSubjectPredictedPapersRoute
  '/ib/$subject/questionbank': typeof IbSubjectQuestionbankRoute
  '/ib/cheatsheets/$id': typeof IbCheatsheetsIdRoute
  '/predicted-papers/$subjectSlug/$paperSlug': typeof PredictedPapersSubjectSlugPaperSlugRoute
  '/ib/$subject/': typeof IbSubjectIndexRoute
  '/ib/cheatsheets/': typeof IbCheatsheetsIndexRoute
  '/predicted-papers/$subjectSlug/': typeof PredictedPapersSubjectSlugIndexRoute
  '/ib/$subject/$noteslug/notes': typeof IbSubjectNoteslugNotesRoute
  '/ib/$subject/$topicslug/flashcards': typeof IbSubjectTopicslugFlashcardsRoute
  '/ib/$subject/$topicslug/questionbank': typeof IbSubjectTopicslugQuestionbankRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/ib/flashcards': typeof IbFlashcardsRoute
  '/ib/notes': typeof IbNotesRoute
  '/ib/questions': typeof IbQuestionsRoute
  '/bots': typeof BotsIndexRoute
  '/ib': typeof IbIndexRoute
  '/predicted-papers': typeof PredictedPapersIndexRoute
  '/chat/$botId/$chatId': typeof ChatBotIdChatIdRoute
  '/ib/$subject/cheatsheets': typeof IbSubjectCheatsheetsRoute
  '/ib/$subject/flashcards': typeof IbSubjectFlashcardsRoute
  '/ib/$subject/notes': typeof IbSubjectNotesRoute
  '/ib/$subject/predicted-papers': typeof IbSubjectPredictedPapersRoute
  '/ib/$subject/questionbank': typeof IbSubjectQuestionbankRoute
  '/ib/cheatsheets/$id': typeof IbCheatsheetsIdRoute
  '/predicted-papers/$subjectSlug/$paperSlug': typeof PredictedPapersSubjectSlugPaperSlugRoute
  '/ib/$subject': typeof IbSubjectIndexRoute
  '/ib/cheatsheets': typeof IbCheatsheetsIndexRoute
  '/predicted-papers/$subjectSlug': typeof PredictedPapersSubjectSlugIndexRoute
  '/ib/$subject/$noteslug/notes': typeof IbSubjectNoteslugNotesRoute
  '/ib/$subject/$topicslug/flashcards': typeof IbSubjectTopicslugFlashcardsRoute
  '/ib/$subject/$topicslug/questionbank': typeof IbSubjectTopicslugQuestionbankRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ib': typeof IbRouteWithChildren
  '/login': typeof LoginRoute
  '/predicted-papers': typeof PredictedPapersRouteWithChildren
  '/ib/$subject': typeof IbSubjectRouteWithChildren
  '/ib/cheatsheets': typeof IbCheatsheetsRouteWithChildren
  '/ib/flashcards': typeof IbFlashcardsRoute
  '/ib/notes': typeof IbNotesRoute
  '/ib/questions': typeof IbQuestionsRoute
  '/bots/': typeof BotsIndexRoute
  '/ib/': typeof IbIndexRoute
  '/predicted-papers/': typeof PredictedPapersIndexRoute
  '/chat/$botId/$chatId': typeof ChatBotIdChatIdRoute
  '/ib/$subject/cheatsheets': typeof IbSubjectCheatsheetsRoute
  '/ib/$subject/flashcards': typeof IbSubjectFlashcardsRoute
  '/ib/$subject/notes': typeof IbSubjectNotesRoute
  '/ib/$subject/predicted-papers': typeof IbSubjectPredictedPapersRoute
  '/ib/$subject/questionbank': typeof IbSubjectQuestionbankRoute
  '/ib/cheatsheets/$id': typeof IbCheatsheetsIdRoute
  '/predicted-papers/$subjectSlug/$paperSlug': typeof PredictedPapersSubjectSlugPaperSlugRoute
  '/ib/$subject/': typeof IbSubjectIndexRoute
  '/ib/cheatsheets/': typeof IbCheatsheetsIndexRoute
  '/predicted-papers/$subjectSlug/': typeof PredictedPapersSubjectSlugIndexRoute
  '/ib/$subject/$noteslug/notes': typeof IbSubjectNoteslugNotesRoute
  '/ib/$subject/$topicslug/flashcards': typeof IbSubjectTopicslugFlashcardsRoute
  '/ib/$subject/$topicslug/questionbank': typeof IbSubjectTopicslugQuestionbankRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ib'
    | '/login'
    | '/predicted-papers'
    | '/ib/$subject'
    | '/ib/cheatsheets'
    | '/ib/flashcards'
    | '/ib/notes'
    | '/ib/questions'
    | '/bots/'
    | '/ib/'
    | '/predicted-papers/'
    | '/chat/$botId/$chatId'
    | '/ib/$subject/cheatsheets'
    | '/ib/$subject/flashcards'
    | '/ib/$subject/notes'
    | '/ib/$subject/predicted-papers'
    | '/ib/$subject/questionbank'
    | '/ib/cheatsheets/$id'
    | '/predicted-papers/$subjectSlug/$paperSlug'
    | '/ib/$subject/'
    | '/ib/cheatsheets/'
    | '/predicted-papers/$subjectSlug/'
    | '/ib/$subject/$noteslug/notes'
    | '/ib/$subject/$topicslug/flashcards'
    | '/ib/$subject/$topicslug/questionbank'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/ib/flashcards'
    | '/ib/notes'
    | '/ib/questions'
    | '/bots'
    | '/ib'
    | '/predicted-papers'
    | '/chat/$botId/$chatId'
    | '/ib/$subject/cheatsheets'
    | '/ib/$subject/flashcards'
    | '/ib/$subject/notes'
    | '/ib/$subject/predicted-papers'
    | '/ib/$subject/questionbank'
    | '/ib/cheatsheets/$id'
    | '/predicted-papers/$subjectSlug/$paperSlug'
    | '/ib/$subject'
    | '/ib/cheatsheets'
    | '/predicted-papers/$subjectSlug'
    | '/ib/$subject/$noteslug/notes'
    | '/ib/$subject/$topicslug/flashcards'
    | '/ib/$subject/$topicslug/questionbank'
  id:
    | '__root__'
    | '/'
    | '/ib'
    | '/login'
    | '/predicted-papers'
    | '/ib/$subject'
    | '/ib/cheatsheets'
    | '/ib/flashcards'
    | '/ib/notes'
    | '/ib/questions'
    | '/bots/'
    | '/ib/'
    | '/predicted-papers/'
    | '/chat/$botId/$chatId'
    | '/ib/$subject/cheatsheets'
    | '/ib/$subject/flashcards'
    | '/ib/$subject/notes'
    | '/ib/$subject/predicted-papers'
    | '/ib/$subject/questionbank'
    | '/ib/cheatsheets/$id'
    | '/predicted-papers/$subjectSlug/$paperSlug'
    | '/ib/$subject/'
    | '/ib/cheatsheets/'
    | '/predicted-papers/$subjectSlug/'
    | '/ib/$subject/$noteslug/notes'
    | '/ib/$subject/$topicslug/flashcards'
    | '/ib/$subject/$topicslug/questionbank'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  IbRoute: typeof IbRouteWithChildren
  LoginRoute: typeof LoginRoute
  PredictedPapersRoute: typeof PredictedPapersRouteWithChildren
  BotsIndexRoute: typeof BotsIndexRoute
  ChatBotIdChatIdRoute: typeof ChatBotIdChatIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/predicted-papers': {
      id: '/predicted-papers'
      path: '/predicted-papers'
      fullPath: '/predicted-papers'
      preLoaderRoute: typeof PredictedPapersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ib': {
      id: '/ib'
      path: '/ib'
      fullPath: '/ib'
      preLoaderRoute: typeof IbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predicted-papers/': {
      id: '/predicted-papers/'
      path: '/'
      fullPath: '/predicted-papers/'
      preLoaderRoute: typeof PredictedPapersIndexRouteImport
      parentRoute: typeof PredictedPapersRoute
    }
    '/ib/': {
      id: '/ib/'
      path: '/'
      fullPath: '/ib/'
      preLoaderRoute: typeof IbIndexRouteImport
      parentRoute: typeof IbRoute
    }
    '/bots/': {
      id: '/bots/'
      path: '/bots'
      fullPath: '/bots/'
      preLoaderRoute: typeof BotsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ib/questions': {
      id: '/ib/questions'
      path: '/questions'
      fullPath: '/ib/questions'
      preLoaderRoute: typeof IbQuestionsRouteImport
      parentRoute: typeof IbRoute
    }
    '/ib/notes': {
      id: '/ib/notes'
      path: '/notes'
      fullPath: '/ib/notes'
      preLoaderRoute: typeof IbNotesRouteImport
      parentRoute: typeof IbRoute
    }
    '/ib/flashcards': {
      id: '/ib/flashcards'
      path: '/flashcards'
      fullPath: '/ib/flashcards'
      preLoaderRoute: typeof IbFlashcardsRouteImport
      parentRoute: typeof IbRoute
    }
    '/ib/cheatsheets': {
      id: '/ib/cheatsheets'
      path: '/cheatsheets'
      fullPath: '/ib/cheatsheets'
      preLoaderRoute: typeof IbCheatsheetsRouteImport
      parentRoute: typeof IbRoute
    }
    '/ib/$subject': {
      id: '/ib/$subject'
      path: '/$subject'
      fullPath: '/ib/$subject'
      preLoaderRoute: typeof IbSubjectRouteImport
      parentRoute: typeof IbRoute
    }
    '/predicted-papers/$subjectSlug/': {
      id: '/predicted-papers/$subjectSlug/'
      path: '/$subjectSlug'
      fullPath: '/predicted-papers/$subjectSlug/'
      preLoaderRoute: typeof PredictedPapersSubjectSlugIndexRouteImport
      parentRoute: typeof PredictedPapersRoute
    }
    '/ib/cheatsheets/': {
      id: '/ib/cheatsheets/'
      path: '/'
      fullPath: '/ib/cheatsheets/'
      preLoaderRoute: typeof IbCheatsheetsIndexRouteImport
      parentRoute: typeof IbCheatsheetsRoute
    }
    '/ib/$subject/': {
      id: '/ib/$subject/'
      path: '/'
      fullPath: '/ib/$subject/'
      preLoaderRoute: typeof IbSubjectIndexRouteImport
      parentRoute: typeof IbSubjectRoute
    }
    '/predicted-papers/$subjectSlug/$paperSlug': {
      id: '/predicted-papers/$subjectSlug/$paperSlug'
      path: '/$subjectSlug/$paperSlug'
      fullPath: '/predicted-papers/$subjectSlug/$paperSlug'
      preLoaderRoute: typeof PredictedPapersSubjectSlugPaperSlugRouteImport
      parentRoute: typeof PredictedPapersRoute
    }
    '/ib/cheatsheets/$id': {
      id: '/ib/cheatsheets/$id'
      path: '/$id'
      fullPath: '/ib/cheatsheets/$id'
      preLoaderRoute: typeof IbCheatsheetsIdRouteImport
      parentRoute: typeof IbCheatsheetsRoute
    }
    '/ib/$subject/questionbank': {
      id: '/ib/$subject/questionbank'
      path: '/questionbank'
      fullPath: '/ib/$subject/questionbank'
      preLoaderRoute: typeof IbSubjectQuestionbankRouteImport
      parentRoute: typeof IbSubjectRoute
    }
    '/ib/$subject/predicted-papers': {
      id: '/ib/$subject/predicted-papers'
      path: '/predicted-papers'
      fullPath: '/ib/$subject/predicted-papers'
      preLoaderRoute: typeof IbSubjectPredictedPapersRouteImport
      parentRoute: typeof IbSubjectRoute
    }
    '/ib/$subject/notes': {
      id: '/ib/$subject/notes'
      path: '/notes'
      fullPath: '/ib/$subject/notes'
      preLoaderRoute: typeof IbSubjectNotesRouteImport
      parentRoute: typeof IbSubjectRoute
    }
    '/ib/$subject/flashcards': {
      id: '/ib/$subject/flashcards'
      path: '/flashcards'
      fullPath: '/ib/$subject/flashcards'
      preLoaderRoute: typeof IbSubjectFlashcardsRouteImport
      parentRoute: typeof IbSubjectRoute
    }
    '/ib/$subject/cheatsheets': {
      id: '/ib/$subject/cheatsheets'
      path: '/cheatsheets'
      fullPath: '/ib/$subject/cheatsheets'
      preLoaderRoute: typeof IbSubjectCheatsheetsRouteImport
      parentRoute: typeof IbSubjectRoute
    }
    '/chat/$botId/$chatId': {
      id: '/chat/$botId/$chatId'
      path: '/chat/$botId/$chatId'
      fullPath: '/chat/$botId/$chatId'
      preLoaderRoute: typeof ChatBotIdChatIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ib/$subject/$topicslug/questionbank': {
      id: '/ib/$subject/$topicslug/questionbank'
      path: '/$topicslug/questionbank'
      fullPath: '/ib/$subject/$topicslug/questionbank'
      preLoaderRoute: typeof IbSubjectTopicslugQuestionbankRouteImport
      parentRoute: typeof IbSubjectRoute
    }
    '/ib/$subject/$topicslug/flashcards': {
      id: '/ib/$subject/$topicslug/flashcards'
      path: '/$topicslug/flashcards'
      fullPath: '/ib/$subject/$topicslug/flashcards'
      preLoaderRoute: typeof IbSubjectTopicslugFlashcardsRouteImport
      parentRoute: typeof IbSubjectRoute
    }
    '/ib/$subject/$noteslug/notes': {
      id: '/ib/$subject/$noteslug/notes'
      path: '/$noteslug/notes'
      fullPath: '/ib/$subject/$noteslug/notes'
      preLoaderRoute: typeof IbSubjectNoteslugNotesRouteImport
      parentRoute: typeof IbSubjectRoute
    }
  }
}

interface IbSubjectRouteChildren {
  IbSubjectCheatsheetsRoute: typeof IbSubjectCheatsheetsRoute
  IbSubjectFlashcardsRoute: typeof IbSubjectFlashcardsRoute
  IbSubjectNotesRoute: typeof IbSubjectNotesRoute
  IbSubjectPredictedPapersRoute: typeof IbSubjectPredictedPapersRoute
  IbSubjectQuestionbankRoute: typeof IbSubjectQuestionbankRoute
  IbSubjectIndexRoute: typeof IbSubjectIndexRoute
  IbSubjectNoteslugNotesRoute: typeof IbSubjectNoteslugNotesRoute
  IbSubjectTopicslugFlashcardsRoute: typeof IbSubjectTopicslugFlashcardsRoute
  IbSubjectTopicslugQuestionbankRoute: typeof IbSubjectTopicslugQuestionbankRoute
}

const IbSubjectRouteChildren: IbSubjectRouteChildren = {
  IbSubjectCheatsheetsRoute: IbSubjectCheatsheetsRoute,
  IbSubjectFlashcardsRoute: IbSubjectFlashcardsRoute,
  IbSubjectNotesRoute: IbSubjectNotesRoute,
  IbSubjectPredictedPapersRoute: IbSubjectPredictedPapersRoute,
  IbSubjectQuestionbankRoute: IbSubjectQuestionbankRoute,
  IbSubjectIndexRoute: IbSubjectIndexRoute,
  IbSubjectNoteslugNotesRoute: IbSubjectNoteslugNotesRoute,
  IbSubjectTopicslugFlashcardsRoute: IbSubjectTopicslugFlashcardsRoute,
  IbSubjectTopicslugQuestionbankRoute: IbSubjectTopicslugQuestionbankRoute,
}

const IbSubjectRouteWithChildren = IbSubjectRoute._addFileChildren(
  IbSubjectRouteChildren,
)

interface IbCheatsheetsRouteChildren {
  IbCheatsheetsIdRoute: typeof IbCheatsheetsIdRoute
  IbCheatsheetsIndexRoute: typeof IbCheatsheetsIndexRoute
}

const IbCheatsheetsRouteChildren: IbCheatsheetsRouteChildren = {
  IbCheatsheetsIdRoute: IbCheatsheetsIdRoute,
  IbCheatsheetsIndexRoute: IbCheatsheetsIndexRoute,
}

const IbCheatsheetsRouteWithChildren = IbCheatsheetsRoute._addFileChildren(
  IbCheatsheetsRouteChildren,
)

interface IbRouteChildren {
  IbSubjectRoute: typeof IbSubjectRouteWithChildren
  IbCheatsheetsRoute: typeof IbCheatsheetsRouteWithChildren
  IbFlashcardsRoute: typeof IbFlashcardsRoute
  IbNotesRoute: typeof IbNotesRoute
  IbQuestionsRoute: typeof IbQuestionsRoute
  IbIndexRoute: typeof IbIndexRoute
}

const IbRouteChildren: IbRouteChildren = {
  IbSubjectRoute: IbSubjectRouteWithChildren,
  IbCheatsheetsRoute: IbCheatsheetsRouteWithChildren,
  IbFlashcardsRoute: IbFlashcardsRoute,
  IbNotesRoute: IbNotesRoute,
  IbQuestionsRoute: IbQuestionsRoute,
  IbIndexRoute: IbIndexRoute,
}

const IbRouteWithChildren = IbRoute._addFileChildren(IbRouteChildren)

interface PredictedPapersRouteChildren {
  PredictedPapersIndexRoute: typeof PredictedPapersIndexRoute
  PredictedPapersSubjectSlugPaperSlugRoute: typeof PredictedPapersSubjectSlugPaperSlugRoute
  PredictedPapersSubjectSlugIndexRoute: typeof PredictedPapersSubjectSlugIndexRoute
}

const PredictedPapersRouteChildren: PredictedPapersRouteChildren = {
  PredictedPapersIndexRoute: PredictedPapersIndexRoute,
  PredictedPapersSubjectSlugPaperSlugRoute:
    PredictedPapersSubjectSlugPaperSlugRoute,
  PredictedPapersSubjectSlugIndexRoute: PredictedPapersSubjectSlugIndexRoute,
}

const PredictedPapersRouteWithChildren = PredictedPapersRoute._addFileChildren(
  PredictedPapersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  IbRoute: IbRouteWithChildren,
  LoginRoute: LoginRoute,
  PredictedPapersRoute: PredictedPapersRouteWithChildren,
  BotsIndexRoute: BotsIndexRoute,
  ChatBotIdChatIdRoute: ChatBotIdChatIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
